name: VALIDATE TERRAFORM TEMPLATES

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: TERRAFORM VALIDATION
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up terraform with version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3

      - name: Terraform init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Format Check
        run: |
          for template in $(find . -name '*.tf'); do
             terraform fmt "$template"
             if ! git diff --exit-code "$template"; then
               echo "Terraform template $template is not correctly formatted."
               exit 1
             fi
           done
        working-directory: ./infra

      - name: Terraform validate
        run: terraform validate
        working-directory: ./infra
